[package]
name = "reth-optimism-primitives"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
description = "OP primitive types"

[lints]
workspace = true

[dependencies]
reth-primitives = { workspace = true, features = ["reth-codec", "optimism"] }
reth-primitives-traits.workspace = true
reth-codecs.workspace = true 
alloy-primitives.workspace = true
alloy-consensus.workspace = true
op-alloy-consensus.workspace = true
alloy-eips.workspace = true
alloy-rlp.workspace = true
derive_more.workspace = true
bytes.workspace = true
serde.workspace = true
arbitrary.workspace = true


[dev-dependencies]
test-fuzz.workspace = true

[features]
arbitrary = ["reth-primitives-traits/arbitrary"]
serde = ["op-alloy-consensus/serde"]
